### ISSUE TITLE
数据存储格式是html，具体怎么存储的呢?

### ISSUE THREAD

**Issue by xuehf** [renhui/RichEditor#2]
您好，我是后台接口开发人员，并不是Android工程师，但是我想问下，
1.如果想要实现再编辑，数据格式具体是怎么存储的，看到您说的以html存储，是如下的逻辑吗?
    a.上传图片后，后端返回图片的url,把这个url以文本的方式插入到编辑框中，如后面有text，可以继续
       如后面还有图片，重复以上，向服务器提交的格式如下
       "我爱我家<img src="http://www.baidu.com/images/abc.png"/>我爱我家，也爱中国<img src="http://www.baidu.com/images/abc.png"/>"
    b.如果是a所述,那么这个展示的时候是webView吗？
    c.那么再编辑的时候如果想对图片本身进行编辑涂鸦,怎么做到? @renhui

**Comment by renhui** [comment]
Html格式存储来存储数据，如：xxxxx  <  img  src="//pic.cnblogs.com/face/u238796.jpg"  />，在展示的时候不是webview去加载数据，而是使用正则将图片和文字进行分割，然后进行展示，使用的Android的 ImageView+TextView。再编辑涂鸦，目前没有这个功能。
